// src/components/Sidebar/Search/Search.tsx
import React, { FC } from 'react';

const Search: FC = () => {
  return (
    <div className="px-[30px] mt-[30px]">
      <div className="bg-[#fff] min-h-[40px] rounded-[15px] flex items-center px-[5px]">
        <img className="w-[20px] h-[20px]" src="./img/search.svg" alt="search" />
        <input className="w-[100%] text-[#000] bg-transparent pl-[5px]" placeholder="Введите имя" />
      </div>
    </div>
  );
};

export default Search;

// src/components/ui/Search/index.vue
<template>
  <label class="input input-sm input-bordered flex items-center gap-2">
    <input type="text" class="grow w-full" placeholder="Search" />
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 16 16"
      fill="currentColor"
      class="h-4 min-w-4 w-4 opacity-70"
    >
      <path
        fill-rule="evenodd"
        d="M9.965 11.026a5 5 0 1 1 1.06-1.06l2.755 2.754a.75.75 0 1 1-1.06 1.06l-2.755-2.754ZM10.5 7a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Z"
        clip-rule="evenodd"
      />
    </svg>
  </label>
</template>
