// src/mob/components/Main/Users/User/User.tsx
import React, { FC } from "react";

interface IUser {
  img: string;
  userName: string;
  onClick: React.MouseEventHandler;
}

const User: FC<IUser> = ({ img, userName, onClick }) => {
  return (
    <div
      className="flex items-center gap-4 px-2 py-3 border-b border-[#ccc] cursor-pointer"
      onClick={onClick}
    >
      <div className="w-[45px] h-[45px] rounded-[50%] overflow-hidden">
        <img className="w-full h-full" src={img} alt={userName} />
      </div>
      <div className="flex flex-col">
        <p className="text-base font-medium">{userName}</p>
      </div>
    </div>
  );
};

export default User;

// src/components/layout/Sidebar/components/ui/User/index.vue
<template>
  <div
    class="flex items-center gap-4 px-6 py-2 cursor-pointer hover:bg-base-100 ease-linear duration-200 active:bg-base-200/95 w-full"
  >
    <div class="w-10 rounded-full overflow-hidden">
      <img
        alt="Tailwind CSS chat bubble component"
        src="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp"
      />
    </div>

    <p class="text-base">Username</p>
  </div>
</template>
