// src/components/Sidebar/UsersList/User/User.tsx
import React, { FC } from 'react';

interface IUser {
  userName: string;
}

const User: FC<IUser> = ({userName}) => {
  return (
    <div className="w-[100%] min-h-[43px] cursor-pointer hover:bg-[#A3C5D8]">
      <div className="flex items-center gap-3 px-[25px] py-[5px]">
        <img className="max-w-[33px] w-[100%] h-[auto] rounded-[50%] overflow-hidden" src="/img/avatar-man.png" alt="avatar" />
        <span className="inline-block text-[12px]">{userName}</span>
      </div>
    </div>
  );
};

export default User;

// src/components/layout/Sidebar/components/ui/User/index.vue
<template>
  <div
    class="flex items-center gap-4 px-6 py-2 cursor-pointer hover:bg-base-100 ease-linear duration-200 active:bg-base-200/95 w-full"
  >
    <div class="w-10 rounded-full overflow-hidden">
      <img
        alt="Tailwind CSS chat bubble component"
        src="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp"
      />
    </div>

    <p class="text-base">Username</p>
  </div>
</template>
