// src/components/layout/Sidebar/components/ui/User/index.vue
<template>
  <div
    class="flex items-center gap-4 px-6 py-2 cursor-pointer hover:bg-base-100 ease-linear duration-200 active:bg-base-200/95 w-full"
  >
    <div class="w-10 rounded-full overflow-hidden">
      <img
        alt="Tailwind CSS chat bubble component"
        src="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp"
      />
    </div>

    <p class="text-base">Username</p>
  </div>
</template>

// src/components/Sidebar/Users/User/User.tsx
import React, { FC } from "react";

interface IUser {
  img: string;
  userName: string;
}

const User: FC<IUser> = ({ img, userName }) => {
  return (
    <div
      className={`bg-["transparent"] w-full min-h-[50px] flex justify-between items-center px-4 py-1 cursor-pointer hover:bg-[rgba(96,169,246,0.15)] relative`}
    >
      <div className="w-[45px] h-[45px] overflow-hidden rounded-[50%]">
        <img className="w-full h-full" src={img} alt={userName} />
      </div>
      <div className="mr-auto ml-2 flex flex-col">
        <p className="text-[16px] font-bold text-[#0D1C2E]">{userName}</p>
      </div>
    </div>
  );
};

export default User;
